version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  web:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mirror
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpacker:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/mirror
    ports:
      - '3035:3035'
